{% set name = "django-elasticsearch-dsl" %}
{% set version = "7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-elasticsearch-dsl-{{ version }}.tar.gz
  sha256: 81c5cd72dcc7424ff4e372db56672863c70c5373624cd6ec2a4e40c83265c6d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elasticsearch-dsl >=7.2.0
    - django >=1.9.6
    - python >=3.6
    - six

test:
  imports:
    - django_elasticsearch_dsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-es/django-elasticsearch-dsl
  summary: Wrapper around elasticsearch-dsl-py for django models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
